### ISSUE TITLE
Building for iOS Simulator, but the embedded framework 'Realm.framework' was built for iOS + iOS Simulator.

### ISSUE THREAD

**Issue by bbakbbak2** [OWASP/iGoat-Swift#26]
Hi, 2020
I have trouble building on simulator.
"Building for iOS Simulator, but the embedded framework 'Realm.framework' was built for iOS + iOS Simulator."

Who know about this issue?

My environment are
- Xcode 12.3
- Big sur 11.0.1

**Comment by z0x0z** [comment]
facing the same above issue ..

**Comment by arnaudberenbaum** [comment]
Hello,
Same problem here on Big Sur 11.1... Can someone know how to bypass this error ?

**Comment by dipti-code** [comment]
i am also facing the same issue
xcode 12.4
Catalina 10.15.7

**Comment by AmandaBSobrinho** [comment]
It is possible to bypass this issue setting Validate Workspace to Yes in the Build Settings tab, as stated here: https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built. However, after that it started showing some architecture errors, and no configuration allows the build to work.

**Comment by swaroopsy** [comment]
Two ways to solve this issue -

1. Use the Legacy Build System (as shown in the screenshot)
![iGoat](https://user-images.githubusercontent.com/9929997/120070564-c8c00c00-c0a8-11eb-97d5-877a2f60e8f6.jpg)

2. Clone from the new branch - https://github.com/OWASP/iGoat-Swift/tree/tech/dependency-update
