### ISSUE TITLE
Error: 'UIApplication' has no member 'statusBarUIView'

### ISSUE THREAD

**Issue by Robihamanto** [OWASP/iGoat-Swift#34]
Try cloning this repo and trying to run the project.
This is my environment:
- Xcode 14.2
- MacBook with M1 Pro.
- Swift 5.7.2

I am getting this error on this line `SideMenuController.swift | L.424`.
```
return UIApplication.shared.statusBarUIView as? UIWindow
```

I found tricky ways to solve this issue to replace those codes this code:
```
        let s = "status"
        let b = "Bar"
        let w = "Window"
        return UIApplication.shared.value(forKey: s+b+w) as? UIWindow
```
Code obtained from [teodorpatras/SideMenuController](https://github.com/teodorpatras/SideMenuController/blob/master/Source/SideMenuController.swift).

Also, don't forget to add `arm64` in excluded architecture in the build settings for Apple Silicon users.

**Comment by imaginaris** [comment]
@Robihamanto 
It looks like `statusBarUIView` definition exists in `Source/Extensions/UIAplication+Extension.swift` file but for some reason that file is not added to the project.

**Comment by ts-robih-robihamanto** [comment]
@imaginaris 
Oh, I found these two classes with the same content:
1. StatusBarView+Extension.swift
2. UIAplication+Extension.swift

Just add one of these class references to the project and the app's working well.
Thank you

**Comment by Robihamanto** [comment]
@imaginaris 

I found these two classes with the same content:
1. StatusBarView+Extension.swift
2. UIAplication+Extension.swift

Just add one of these class references to the project and the app's working well.
Thank you
